# Jekyll configuration for ChessML Documentation
title: ChessML
description: A bitboard-based chess engine in OCaml with comprehensive chess programming guides
url: https://alexanderbrevig.github.io
baseurl: /chessml

# Theme
theme: just-the-docs

# Color scheme (options: nil, dark, light)
color_scheme: dark

# Logo (uncomment when you add a logo)
# logo: "/assets/images/chessml-logo.png"

# Callouts (for tips, warnings, notes)
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Enable navigation
nav_enabled: true
nav_sort: case_insensitive # or case_sensitive

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Mermaid diagrams support
mermaid:
  version: "10.6.1"

# Aux links (appears in top right)
aux_links:
  "View on GitHub":
    - "//github.com/AlexanderBrevig/ChessML"
  "Report Issue":
    - "//github.com/AlexanderBrevig/ChessML/issues/new"

# Aux links position
aux_links_new_tab: true

# Footer
footer_content: 'Copyright &copy; 2025 Alexander Brevig. Distributed under the <a href="https://github.com/AlexanderBrevig/ChessML/blob/main/LICENSE">MIT License</a>.'

# Enable copy button for code blocks
enable_copy_code_button: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Heading anchors
heading_anchors: true

# Default settings
defaults:
  - scope:
      path: "docs"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"

# Kramdown settings
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    default_lang: ocaml
    # Use monokai.sublime theme (closest to Catppuccin aesthetic)
    # Other options: gruvbox.dark, base16.monokai.dark, github.dark
    block:
      line_numbers: false
      start_line: 1

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Emoji settings
emoji:
  src: "/assets/images/emoji"

# Exclude from processing
exclude:
  - node_modules/
  - vendor/
  - _build/
  - bin/
  - lib/
  - test/
  - examples/
  - scripts/
  - openings/
  - "*.opam"
  - dune-project
  - Justfile
  - "*.pgn"
  - "*.txt"
  - CONTRIBUTING.md
